# Generated by Django 5.1.1 on 2024-10-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flo',
            new_name='Company',
        ),
    ]
