# Generated by Django 5.1.1 on 2024-10-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0002_rename_flo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
