# Generated by Django 5.1.1 on 2024-10-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0003_company_amount_paid_company_amount_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='amount_total',
            new_name='fuel_allocation',
        ),
    ]
