# Generated by Django 5.1.1 on 2024-10-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0004_rename_amount_total_company_fuel_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='fuel_type',
        ),
    ]
