# Generated by Django 5.1.1 on 2024-10-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0005_rename_city_company_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notification_threshold',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flo.company')),
            ],
        ),
    ]
