# Generated by Django 5.1.1 on 2024-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0007_rename_amount_paid_company_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fuel_type',
            field=models.CharField(choices=[('unleaded_petrol', 'Unleaded Petrol'), ('blended_petrol', 'Blended Petrol'), ('diesel_50', 'Diesel 50'), ('regular_diesel', 'Regular Diesel')], max_length=100),
        ),
    ]
