# Generated by Django 5.1.1 on 2024-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0010_company_init_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_allocation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='init_fuel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='amount_withdrawn',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
