# Generated by Django 5.1.1 on 2024-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0011_alter_company_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
